---
title: "Final Project"
author: "Riley Maher"
date: "3/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tm)
library(stopwords)
library(tokenizers)
library(dplyr)
library(tidytext)
library(sentimentr)
library(gender)
```

```{r}
# News Train
news_train <- read.csv('train.csv')
news_train$id <- NULL

news_test <- read.csv('test.csv')
news_test$id <- NULL

head(news_train)
```

```{r}
news_train$cleaned_title <- tolower(news_train$title)
news_train$cleaned_title <- removePunctuation(news_train$cleaned_title)
news_train$cleaned_title <- stripWhitespace(news_train$cleaned_title)
news_train$title_character_length <- lapply(news_train$cleaned_title, nchar)
news_train$cleaned_title <- tokenize_words(news_train$cleaned_title, stopwords = stopwords::stopwords("en"))
news_train$cleaned_title <- lapply(news_train$cleaned_title, tokenize_word_stems)
news_train$title_word_length <- lapply(news_train$cleaned_title, length)
```


```{r}
news_train$cleaned_text <- tolower(news_train$text)
news_train$cleaned_text <- removePunctuation(news_train$cleaned_text)
news_train$cleaned_text <- stripWhitespace(news_train$cleaned_text)
# news_train$text_sentiment <- sentiment(news_train$cleaned_text)$sentiment
news_train$text_character_length <- lapply(news_train$cleaned_text, nchar)
news_train$cleaned_text <- tokenize_words(news_train$cleaned_text, stopwords = stopwords::stopwords("en"))
news_train$cleaned_text <- lapply(news_train$cleaned_text, tokenize_word_stems)
news_train$text_word_length <- lapply(news_train$cleaned_text, length)
```

```{r}
head(news_train_sample)
```

```{r}
news_train$cleaned_text[1]
# paste(, collapse=' ')
# sentiment('I am madly in love')$sentiment
```


```{r}
View(news_train)
```

# Potential Things to Add

## Must Haves

-Bigrams
-Trigrams
-Sentiment of Text

## Nice to Haves

-Parts of Speech Count
